### ISSUE TITLE
UI "Waiting for response ..." forever on query with empty result

### ISSUE THREAD

**Issue by hannahbast** [jbuerklin/qleverUI#15]
When a query yields an empty result, the UI shows the animated "Waiting for response ..." forever.

I think the reason is the following line (282 in the version of the code, where I encountered the error) in qleverUI.js, which throws an error if the result is empty. Not sure though why the UI stalls in the following then.

```if (/wktLiteral/.test(result.res[0][columns.length - 1])) {```

**Comment by jbuerklin** [comment]
Fixed in 7f6e9d0f5980016f7c7d05e95ecdac6a01c08eac
