### ISSUE TITLE
Executing a query changes the GET request URL to a POST request URL

### ISSUE THREAD

**Issue by graue70** [jbuerklin/qleverUI#25]
If I open e. g. [this URL](http://qlever.informatik.uni-freiburg.de/Wikidata_Full/?query=PREFIX+wd%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0APREFIX+wdt%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT+%3Fperson_id+%3Fperson+%28COUNT%28%3Fprofession_id%29+as+%3Fcount%29+%28GROUP_CONCAT%28%3Fprofession%3B+separator%3D%22%2C+%22%29+as+%3Fprofessions%29+WHERE+%7B%0A++%3Fperson_id+wdt%3AP31+wd%3AQ5+.%0A++%3Fperson_id+wdt%3AP106+%3Fprofession_id+.%0A++%3Fprofession_id+rdfs%3Alabel+%3Fprofession+.%0A++%3Fperson_id+rdfs%3Alabel+%3Fperson+.%0A++FILTER+%28lang%28%3Fperson%29+%3D+%22en%22%29+.%0A++FILTER+%28lang%28%3Fprofession%29+%3D+%22en%22%29%0A%7D%0AGROUP+BY+%3Fperson_id+%3Fperson%0AORDER+BY+DESC%28%3Fcount%29) and click on 'Execute', the URL changes to e. g. this one: http://qlever.informatik.uni-freiburg.de/Wikidata_Full/g5DPR2

That is surprising behavior. Is it intentional? I would expect the URL not to change when executing the query.

**Comment by jbuerklin** [comment]
Fixed in 70922c867fb318aa377e63d4b139b7d926af3c0a  
The URL will not be overwritten when the `query` search parameter equals the executed query
