### ISSUE TITLE
Improve support for comments in queries

### ISSUE THREAD

**Issue by graue70** [jbuerklin/qleverUI#5]
Comments are already supported, meaning they can be typed and do not raise an error.

It would, however, be nice to have them colored differently than predicates.

Also, there is an issue with autocompletion if one types `#`. There is autocompletion happening and there are actual (seemingly correct) results whose labels start with a hash sign. I'm not sure whether this can be solved somehow, meaning whether it can be possible for the UI to recognize and differentiate between wanting for example `wd:Q12886367` (#Beautiful) and typing a comment.

**Comment by graue70** [comment]
This is how comments look in Visual Studio Code with the extension `SPARQL Language Server (with Stardog extensions)`:
![Screenshot_vscode](https://user-images.githubusercontent.com/23035329/72082237-2317cb80-3300-11ea-82ed-990dd19c563c.png)

Of course, they don't have the autocompletion problem I mentioned above.

**Comment by jbuerklin** [comment]
I don't quite see a good solution for the autocomplete problem, yet.
I'll think about it and add syntax highlighting for comments in the meantime.

**Comment by graue70** [comment]
The coloring of comments is implemented.

I'm closing this issue because it isn't clear whether there even exists a solution for the autocompletion problem.
